pages:
  stage: deploy
  before_script: 
  - 'git push --force --mirror git@github.com:TLOxyz/Guess-What-I-Said.git'
  script:
  - mkdir -p /var/www/site/app/Guess-What-I-Said
  - nice jekyll build --incremental -d /var/www/site/app/Guess-What-I-Said
  only:
  - master